version: 2
jobs:
  build:
    docker:
      - image: shepmaster/rust-nightly
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }}
            - v1-cargo-cache-{{ arch }}

      # Diagnostics
      - run:
          name: Show versions
          command: rustc --version && cargo --version

      # Default features
      - run:
          name: Build (default)
          command: cargo build
      - run:
          name: Test (default)
          command: cargo test

      # Feature: measurements
      - run:
          name: Build (measurements)
          command: cargo build --features measurements
      - run:
          name: Test (measurements)
          command: cargo test --features measurements

      # Save cache
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - ffi/target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ arch }}
          paths:
            - target
            - ffi/target
            - /usr/local/cargo
